{
    "minimumReleaseAge": 10080,
    "packages": [
        "**",
        # exclude the git submodules, they managed manually
        "!packages/node-websocket/withastro/astro/**",
        "!packages/bun-websocket/NuroDev/astro-bun/**",
        "!packages/cloudflare-websocket/withastro/astro/**",
        "!packages/deno-websocket/denoland/deno-astro-adapter/**"
    ]
}
