{
    "packages": [
        "**",
        # exclude the git submodules, they managed manually
        "!packages/node-websocket/withastro/adapters/**",
        "!packages/bun-websocket/NuroDev/astro-bun/**",
    ]
}
