name: Test

on:
  workflow_call:
    inputs:
      node:
        description: Node.js version
        type: string
        default: "20"
      os:
        description: Operating system
        type: string
        default: ubuntu-latest
      check:
        description: Type-check with tsc
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      node:
        description: "Node.js version"
        type: string
        default: "20"
      os:
        description: "Operating system"
        default: ubuntu-latest
        type: choice
        options: 
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-latest
          - macos-15
          - macos-14
          - macos-13
          - macos-12
          - windows-latest
          - windows-2022
          - windows-2019
      check:
        description: Type-check with tsc
        type: boolean
        default: false
env:
  ASTRO_TELEMETRY_DISABLED: true

jobs:
  test:
    name: "Test"
    runs-on: ${{ inputs.os }}
    env:
      NODE_VERSION: ${{ inputs.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      
      - name: Setup Node ${{ inputs.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node }}
          cache: "pnpm"
      
      - name: Setup Bun
        if: ${{ inputs.node == 23 }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.40
      
      - uses: denoland/setup-deno@v2
        with:
          deno-version: 2.1.4
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Init submodules
        run: sh .github/workflows/init-submodules.sh
      
      - name: Check
        if: ${{ inputs.check }}
        run: pnpm run check
      
      - name: Test
        run: pnpm run test
